name: CI/CD for PHP Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Validate PHP files
      run: |
        find . -name "*.php" -exec php -l {} \;

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: php-project
        path: .

#TESTING